# Site settings
title: merge_andvary
description: > 
  General ramblings and mutterings about postgraduate higher degree research
baseurl: "" 
url: "mergeandvary.github.io"
image: http://www.happytrips.com/photo/37773895/Walk-along-the-Berlin-Wall.jpg
imagesrc: happytrips.com

# twitter_username: jekyllrb
# github_username:  mergeandvary
# email: your-email@domain.com

# Build settings
markdown: kramdown
