# Site settings
title: mergeandvary.x
description: > 
  Postgraduate HDR ramblings and mutterings
baseurl: "" 
url: "mergeandvary.github.io"
image: riverafrescos.jpg
imagesrc: Wikimedia (Diego Rivera - Detroit Industry Mural)

# twitter_username: jekyllrb
# github_username:  mergeandvary
# email: your-email@domain.com

# Build settings
markdown: kramdown
