# Site settings
title: mergeandvary.x
description: > 
  Postgraduate HDR ramblings and mutterings
baseurl: "" 
url: "mergeandvary.github.io"
image: chesscafe.jpg
imagesrc: Wikimedia (Jean Henry Marlet - The Famous Chess Match)

# twitter_username: jekyllrb
# github_username:  mergeandvary
# email: your-email@domain.com

# Build settings
markdown: kramdown
